name: CI on Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # Add steps for setting up your project environment
    # For example, if you're using Node.js:
    - name: Set up Node.js
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest # Specify your Node.js version

    # Install dependencies
    - name: Install dependencies
      run: bun i

    # Add your build script
    - name: Build
      run: bun run build:server && bun run build:client

    # Add your test script
    - name: Test
      run: bun test
