[jsx]
jsx = "react-jsx"
jsxFactory = "h"
jsxFragment = "Fragment"
jsxImportSource = "react"
smol = true
logLevel = "debug"

[define]
process.env.NODE_ENV = "development"

[loader]
".bagel" = "tsx"

[test]
root = "./src/tests"
preload = ["./src/utils/testSetup.ts"]
smol = true
coverage = true
coverageThreshold = { line = 0.7, function = 0.8, statement = 0.9 }
coverageSkipTestFiles = true

[install]
optional = true
dev = true
peer = true
production = false
exact = false
auto = "auto"
frozenLockfile = false
dryRun = false
globalDir = "~/.bun/install/global"
globalBinDir = "~/.bun/bin"
registry = "https://registry.npmjs.org"

# Cache settings
[install.cache]
dir = "~/.bun/install/cache"
disable = false
disableManifest = false

# Lockfile settings
[install.lockfile]
save = true
print = "yarn"